---
- hosts: mythic
  become: yes
  tasks:
    - name: Update and install prerequisites
      apt:
        update_cache: yes
        name:
          - make
        state: present

    - name: Clone the Mythic repository
      shell: |
        cd /opt/
        sudo git clone https://github.com/its-a-feature/Mythic --depth 1

    - name: Install Docker  and Starting
      shell: |
        cd /opt/Mythic
        sudo ./install_docker_ubuntu.sh
        sudo systemctl start docker

    - name: Install and Building Mythic-CLI
      shell: |
        cd /opt/Mythic
        sudo make

    - name: Install Mythic Agents and Profiles (Default)
      shell: |
        cd /opt/Mythic
        sudo ./mythic-cli install github https://github.com/MythicAgents/Apollo.git
        sudo ./mythic-cli install github https://github.com/MythicAgents/bloodhound.git
        sudo ./mythic-cli install github https://github.com/MythicAgents/poseidon.git
        sudo ./mythic-cli install github https://github.com/MythicC2Profiles/http


    - name: Start Mythic services
      shell: |
        cd /opt/Mythic
        sudo ./mythic-cli start
